on:
  push:
    branches:
      - !dev
      - !gh-pages

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "hello world"

      - name: Run a build
        uses: ./.github/workflows/build
